//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DTO
{
    using System;
    using System.Collections.Generic;
    
    public partial class CHITIETSUDUNG
    {
        public string TenDangNhap { get; set; }
        public string SoMay { get; set; }
        public System.DateTime BatDau { get; set; }
        public Nullable<System.DateTime> KetThuc { get; set; }
    
        public virtual MAYTINH MAYTINH { get; set; }
        public virtual TAIKHOAN TAIKHOAN { get; set; }
    }
}
