//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DTO
{
    using System;
    using System.Collections.Generic;
    
    public partial class DanhSachKhuyenMai
    {
        public string MaKM { get; set; }
        public string TenChTrinh { get; set; }
        public int TyLeKM { get; set; }
        public int SoTienToiThieuApDung { get; set; }
        public int KMToiDa { get; set; }
        public System.DateTime ThoiGianBatDau { get; set; }
        public System.DateTime ThoiGianKetThuc { get; set; }
        public int MaLoaiKM { get; set; }
        public string TenLoai { get; set; }
    }
}
