//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DTO
{
    using System;
    using System.Collections.Generic;
    
    public partial class DanhSachMayTinh
    {
        public string SoMay { get; set; }
        public string TenLoaiMay { get; set; }
        public int MaLoaiMay { get; set; }
        public string TrangThai { get; set; }
        public System.DateTime NgayLapDat { get; set; }
        public double TongTGSD { get; set; }
    }
}
