//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DTO
{
    using System;
    using System.Collections.Generic;
    
    public partial class DVDOUONG
    {
        public string MaDV { get; set; }
        public int DonGia { get; set; }
        public string TenDoUong { get; set; }
        public Nullable<bool> BestSeller { get; set; }
        public string TrangThai { get; set; }
    
        public virtual DICHVU DICHVU { get; set; }
    }
}
