//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DTO
{
    using System;
    using System.Collections.Generic;
    
    public partial class DVTHECAO
    {
        public string MaDV { get; set; }
        public int MenhGia { get; set; }
        public string LoaiThe { get; set; }
    
        public virtual DICHVU DICHVU { get; set; }
    }
}
