//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DTO
{
    using System;
    using System.Collections.Generic;
    
    public partial class HOADON
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HOADON()
        {
            this.CHITIETDVs = new HashSet<CHITIETDV>();
        }
    
        public string MaHD { get; set; }
        public Nullable<int> TongThanhToan { get; set; }
        public string PhuongThucTT { get; set; }
        public string TrangThai { get; set; }
        public System.DateTime NgayLap { get; set; }
        public string LoaiHoaDon { get; set; }
        public Nullable<int> SoTienNap { get; set; }
        public Nullable<int> TienCongThem { get; set; }
        public Nullable<int> TienDuocGiam { get; set; }
        public string TenDangNhap { get; set; }
        public Nullable<int> MaNV { get; set; }
        public string MaKM { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CHITIETDV> CHITIETDVs { get; set; }
        public virtual KHUYENMAI KHUYENMAI { get; set; }
        public virtual NHANVIEN NHANVIEN { get; set; }
        public virtual TAIKHOAN TAIKHOAN { get; set; }
    }
}
