//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DTO
{
    using System;
    using System.Collections.Generic;
    
    public partial class LINHKIEN
    {
        public int MaLoaiMay { get; set; }
        public string TenLinhKien { get; set; }
        public string ChiTietLK { get; set; }
        public int SoLuong { get; set; }
    
        public virtual LOAIMAY LOAIMAY { get; set; }
    }
}
