//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DTO
{
    using System;
    using System.Collections.Generic;
    
    public partial class MAYTINH
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MAYTINH()
        {
            this.CHITIETSUDUNGs = new HashSet<CHITIETSUDUNG>();
        }
    
        public string SoMay { get; set; }
        public string TrangThai { get; set; }
        public System.DateTime NgayLapDat { get; set; }
        public int MaLoaiMay { get; set; }
    
        public virtual LOAIMAY LOAIMAY { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CHITIETSUDUNG> CHITIETSUDUNGs { get; set; }
    }
}
