//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DTO
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    using System.Windows.Forms;

    public partial class QuanLyTiemNetEntities : DbContext
    {
        private static QuanLyTiemNetEntities instance;

        // Property Instance (Singleton pattern)
        public static QuanLyTiemNetEntities Instance
        {
            get
            {
                if (instance == null)
                    instance = new QuanLyTiemNetEntities();
                return instance;
            }
            set
            {
                instance = value;
            }
        }

        // Constructor mặc định (sử dụng chuỗi kết nối trong App.config)
        public QuanLyTiemNetEntities()
            : base("name=QuanLyTiemNetEntities")
        {
        }

        // Constructor cho phép truyền chuỗi kết nối động
        public QuanLyTiemNetEntities(string connectionString)
            : base(connectionString)
        {
        }

        // Thực hiện việc truy vấn SP hoặc các thao tác trên DB ở đây
        // Ví dụ: Gọi Stored Procedure sp_helpuser
        public class UserRole
        {
            public string UserName { get; set; }
            public string RoleName { get; set; }
        }

        public string GetRoleFromUsername(string username)
        {
            try
            {
                var result = this.Database.SqlQuery<UserRole>(
                    "EXEC sp_helpuser {0}", username).ToList();

                if (result.Count > 0)
                {
                    var row = result[0];
                    return row.RoleName ?? "Không xác định";
                }

                return "Không tìm thấy người dùng";
            }
            catch (Exception ex)
            {
                //MessageBox.Show("Lỗi khi lấy thông tin người dùng: " + ex.Message, "Lỗi", MessageBoxButtons.OK, MessageBoxIcon.Error);
                return null;
            }
        }



        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            // Giữ nguyên để tránh EF Code First can thiệp
            throw new UnintentionalCodeFirstException();
        }
        public virtual DbSet<CHITIETDV> CHITIETDVs { get; set; }
        public virtual DbSet<DICHVU> DICHVUs { get; set; }
        public virtual DbSet<DVDOAN> DVDOANs { get; set; }
        public virtual DbSet<DVDOUONG> DVDOUONGs { get; set; }
        public virtual DbSet<DVTHECAO> DVTHECAOs { get; set; }
        public virtual DbSet<HOADON> HOADONs { get; set; }
        public virtual DbSet<KHUYENMAI> KHUYENMAIs { get; set; }
        public virtual DbSet<LINHKIEN> LINHKIENs { get; set; }
        public virtual DbSet<LOAIKM> LOAIKMs { get; set; }
        public virtual DbSet<LOAIMAY> LOAIMAYs { get; set; }
        public virtual DbSet<MAYTINH> MAYTINHs { get; set; }
        public virtual DbSet<NHANVIEN> NHANVIENs { get; set; }
        public virtual DbSet<TAIKHOAN> TAIKHOANs { get; set; }
        public virtual DbSet<CHITIETSUDUNG> CHITIETSUDUNGs { get; set; }
        public virtual DbSet<DanhSachKhuyenMai> DanhSachKhuyenMais { get; set; }
        public virtual DbSet<DanhSachLoaiKhuyenMai> DanhSachLoaiKhuyenMais { get; set; }
        public virtual DbSet<DanhSachLoaiMay> DanhSachLoaiMays { get; set; }
        public virtual DbSet<DanhSachMayTinh> DanhSachMayTinhs { get; set; }
        public virtual DbSet<DanhSachNhanVien> DanhSachNhanViens { get; set; }
        public virtual DbSet<DanhSachTaiKhoan> DanhSachTaiKhoans { get; set; }
        public virtual DbSet<Top5DoAn> Top5DoAn { get; set; }
        public virtual DbSet<Top5DoAnItNhat> Top5DoAnItNhat { get; set; }
        public virtual DbSet<Top5DoUong> Top5DoUong { get; set; }
        public virtual DbSet<Top5DoUongItNhat> Top5DoUongItNhat { get; set; }
        public virtual DbSet<View_DichVuDoAn> View_DichVuDoAn { get; set; }
        public virtual DbSet<View_DichVuDoUong> View_DichVuDoUong { get; set; }
        public virtual DbSet<View_DichVuTheCao> View_DichVuTheCao { get; set; }
    
        [DbFunction("QuanLyTiemNetEntities", "fn_LayTaiKhoanTheoTenDangNhap")]
        public virtual IQueryable<fn_LayTaiKhoanTheoTenDangNhap_Result> fn_LayTaiKhoanTheoTenDangNhap(string tenDangNhap)
        {
            var tenDangNhapParameter = tenDangNhap != null ?
                new ObjectParameter("TenDangNhap", tenDangNhap) :
                new ObjectParameter("TenDangNhap", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<fn_LayTaiKhoanTheoTenDangNhap_Result>("[QuanLyTiemNetEntities].[fn_LayTaiKhoanTheoTenDangNhap](@TenDangNhap)", tenDangNhapParameter);
        }
    
        [DbFunction("QuanLyTiemNetEntities", "fn_TimKhachHangCuaNam")]
        public virtual IQueryable<fn_TimKhachHangCuaNam_Result> fn_TimKhachHangCuaNam(Nullable<int> nam)
        {
            var namParameter = nam.HasValue ?
                new ObjectParameter("Nam", nam) :
                new ObjectParameter("Nam", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<fn_TimKhachHangCuaNam_Result>("[QuanLyTiemNetEntities].[fn_TimKhachHangCuaNam](@Nam)", namParameter);
        }
    
        [DbFunction("QuanLyTiemNetEntities", "fn_TimKhachHangCuaThang")]
        public virtual IQueryable<fn_TimKhachHangCuaThang_Result> fn_TimKhachHangCuaThang(Nullable<int> thang, Nullable<int> nam)
        {
            var thangParameter = thang.HasValue ?
                new ObjectParameter("Thang", thang) :
                new ObjectParameter("Thang", typeof(int));
    
            var namParameter = nam.HasValue ?
                new ObjectParameter("Nam", nam) :
                new ObjectParameter("Nam", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<fn_TimKhachHangCuaThang_Result>("[QuanLyTiemNetEntities].[fn_TimKhachHangCuaThang](@Thang, @Nam)", thangParameter, namParameter);
        }
    
        [DbFunction("QuanLyTiemNetEntities", "fn_TimKiemDVDA")]
        public virtual IQueryable<fn_TimKiemDVDA_Result> fn_TimKiemDVDA(string query)
        {
            var queryParameter = query != null ?
                new ObjectParameter("query", query) :
                new ObjectParameter("query", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<fn_TimKiemDVDA_Result>("[QuanLyTiemNetEntities].[fn_TimKiemDVDA](@query)", queryParameter);
        }
    
        [DbFunction("QuanLyTiemNetEntities", "fn_TimKiemDVDU")]
        public virtual IQueryable<fn_TimKiemDVDU_Result> fn_TimKiemDVDU(string query)
        {
            var queryParameter = query != null ?
                new ObjectParameter("query", query) :
                new ObjectParameter("query", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<fn_TimKiemDVDU_Result>("[QuanLyTiemNetEntities].[fn_TimKiemDVDU](@query)", queryParameter);
        }
    
        [DbFunction("QuanLyTiemNetEntities", "fn_TimKiemDVTC")]
        public virtual IQueryable<fn_TimKiemDVTC_Result> fn_TimKiemDVTC(string query)
        {
            var queryParameter = query != null ?
                new ObjectParameter("query", query) :
                new ObjectParameter("query", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<fn_TimKiemDVTC_Result>("[QuanLyTiemNetEntities].[fn_TimKiemDVTC](@query)", queryParameter);
        }
    
        [DbFunction("QuanLyTiemNetEntities", "fn_TimKiemNhanVien")]
        public virtual IQueryable<fn_TimKiemNhanVien_Result> fn_TimKiemNhanVien(string info)
        {
            var infoParameter = info != null ?
                new ObjectParameter("Info", info) :
                new ObjectParameter("Info", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<fn_TimKiemNhanVien_Result>("[QuanLyTiemNetEntities].[fn_TimKiemNhanVien](@Info)", infoParameter);
        }
    
        [DbFunction("QuanLyTiemNetEntities", "fn_TimKMChoHDNapTien")]
        public virtual IQueryable<fn_TimKMChoHDNapTien_Result> fn_TimKMChoHDNapTien(Nullable<int> tongThanhToan)
        {
            var tongThanhToanParameter = tongThanhToan.HasValue ?
                new ObjectParameter("TongThanhToan", tongThanhToan) :
                new ObjectParameter("TongThanhToan", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<fn_TimKMChoHDNapTien_Result>("[QuanLyTiemNetEntities].[fn_TimKMChoHDNapTien](@TongThanhToan)", tongThanhToanParameter);
        }
    
        [DbFunction("QuanLyTiemNetEntities", "fn_timLkTheoLoaiMay")]
        public virtual IQueryable<fn_timLkTheoLoaiMay_Result> fn_timLkTheoLoaiMay(Nullable<int> maLoaiMay)
        {
            var maLoaiMayParameter = maLoaiMay.HasValue ?
                new ObjectParameter("MaLoaiMay", maLoaiMay) :
                new ObjectParameter("MaLoaiMay", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<fn_timLkTheoLoaiMay_Result>("[QuanLyTiemNetEntities].[fn_timLkTheoLoaiMay](@MaLoaiMay)", maLoaiMayParameter);
        }
    
        [DbFunction("QuanLyTiemNetEntities", "fn_TimNhanVienCuaNam")]
        public virtual IQueryable<fn_TimNhanVienCuaNam_Result> fn_TimNhanVienCuaNam(Nullable<int> nam)
        {
            var namParameter = nam.HasValue ?
                new ObjectParameter("Nam", nam) :
                new ObjectParameter("Nam", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<fn_TimNhanVienCuaNam_Result>("[QuanLyTiemNetEntities].[fn_TimNhanVienCuaNam](@Nam)", namParameter);
        }
    
        [DbFunction("QuanLyTiemNetEntities", "fn_TimNhanVienCuaThang")]
        public virtual IQueryable<fn_TimNhanVienCuaThang_Result> fn_TimNhanVienCuaThang(Nullable<int> thang, Nullable<int> nam)
        {
            var thangParameter = thang.HasValue ?
                new ObjectParameter("Thang", thang) :
                new ObjectParameter("Thang", typeof(int));
    
            var namParameter = nam.HasValue ?
                new ObjectParameter("Nam", nam) :
                new ObjectParameter("Nam", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<fn_TimNhanVienCuaThang_Result>("[QuanLyTiemNetEntities].[fn_TimNhanVienCuaThang](@Thang, @Nam)", thangParameter, namParameter);
        }
    
        [DbFunction("QuanLyTiemNetEntities", "fn_TinhDoanhThuNhanVienTheoThang")]
        public virtual IQueryable<fn_TinhDoanhThuNhanVienTheoThang_Result> fn_TinhDoanhThuNhanVienTheoThang(Nullable<int> thang, Nullable<int> nam)
        {
            var thangParameter = thang.HasValue ?
                new ObjectParameter("Thang", thang) :
                new ObjectParameter("Thang", typeof(int));
    
            var namParameter = nam.HasValue ?
                new ObjectParameter("Nam", nam) :
                new ObjectParameter("Nam", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<fn_TinhDoanhThuNhanVienTheoThang_Result>("[QuanLyTiemNetEntities].[fn_TinhDoanhThuNhanVienTheoThang](@Thang, @Nam)", thangParameter, namParameter);
        }
    
        [DbFunction("QuanLyTiemNetEntities", "fn_XemChiTietHoaDonDichVu")]
        public virtual IQueryable<fn_XemChiTietHoaDonDichVu_Result> fn_XemChiTietHoaDonDichVu(string maHD)
        {
            var maHDParameter = maHD != null ?
                new ObjectParameter("MaHD", maHD) :
                new ObjectParameter("MaHD", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<fn_XemChiTietHoaDonDichVu_Result>("[QuanLyTiemNetEntities].[fn_XemChiTietHoaDonDichVu](@MaHD)", maHDParameter);
        }
    
        [DbFunction("QuanLyTiemNetEntities", "func_timKiemLoaiMay")]
        public virtual IQueryable<func_timKiemLoaiMay_Result> func_timKiemLoaiMay(string tenLoaiMay)
        {
            var tenLoaiMayParameter = tenLoaiMay != null ?
                new ObjectParameter("TenLoaiMay", tenLoaiMay) :
                new ObjectParameter("TenLoaiMay", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<func_timKiemLoaiMay_Result>("[QuanLyTiemNetEntities].[func_timKiemLoaiMay](@TenLoaiMay)", tenLoaiMayParameter);
        }
    
        [DbFunction("QuanLyTiemNetEntities", "func_timKiemMayTinh")]
        public virtual IQueryable<func_timKiemMayTinh_Result> func_timKiemMayTinh(string soMay)
        {
            var soMayParameter = soMay != null ?
                new ObjectParameter("SoMay", soMay) :
                new ObjectParameter("SoMay", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<func_timKiemMayTinh_Result>("[QuanLyTiemNetEntities].[func_timKiemMayTinh](@SoMay)", soMayParameter);
        }
    
        [DbFunction("QuanLyTiemNetEntities", "func_TinhDoanhThu12ThangGanNhat")]
        public virtual IQueryable<func_TinhDoanhThu12ThangGanNhat_Result> func_TinhDoanhThu12ThangGanNhat()
        {
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<func_TinhDoanhThu12ThangGanNhat_Result>("[QuanLyTiemNetEntities].[func_TinhDoanhThu12ThangGanNhat]()");
        }

        [DbFunction("QuanLyTiemNetEntities", "fn_TKMoiTrongThang")]
        public virtual IQueryable<int> fn_TKMoiTrongThang()
        {
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<int>("[QuanLyTiemNetEntities].[fn_TKMoiTrongThang]()");
        }

        [DbFunction("QuanLyTiemNetEntities", "fn_TinhTongMayHD")]
        public virtual IQueryable<int> fn_TinhTongMayHD()
        {
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<int>("[QuanLyTiemNetEntities].[fn_TinhTongMayHD]()");
        }

        [DbFunction("QuanLyTiemNetEntities", "fn_GetGiaTienTheoGio")]
        public virtual IQueryable<int> fn_GetGiaTienTheoGio(string soMay)
        {
            var soMayParam = new ObjectParameter("SoMay", soMay);
            return ((IObjectContextAdapter)this)
                   .ObjectContext
                   .CreateQuery<int>("[QuanLyTiemNetEntities].[fn_GetGiaTienTheoGio](@SoMay)", soMayParam);
        }


        public virtual int proc_doiMkNv(string sDT, string matKhau)
        {
            var sDTParameter = sDT != null ?
                new ObjectParameter("SDT", sDT) :
                new ObjectParameter("SDT", typeof(string));
    
            var matKhauParameter = matKhau != null ?
                new ObjectParameter("MatKhau", matKhau) :
                new ObjectParameter("MatKhau", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("proc_doiMkNv", sDTParameter, matKhauParameter);
        }
    
        public virtual int proc_HoanTatHD(string maHD)
        {
            var maHDParameter = maHD != null ?
                new ObjectParameter("MaHD", maHD) :
                new ObjectParameter("MaHD", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("proc_HoanTatHD", maHDParameter);
        }
    
        public virtual int proc_HuyHD(string maHD)
        {
            var maHDParameter = maHD != null ?
                new ObjectParameter("MaHD", maHD) :
                new ObjectParameter("MaHD", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("proc_HuyHD", maHDParameter);
        }
    
        public virtual int proc_KhoaTaiKhoan(string tenDangNhap)
        {
            var tenDangNhapParameter = tenDangNhap != null ?
                new ObjectParameter("TenDangNhap", tenDangNhap) :
                new ObjectParameter("TenDangNhap", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("proc_KhoaTaiKhoan", tenDangNhapParameter);
        }
    
        public virtual ObjectResult<proc_layMayTheoMaLoai_Result> proc_layMayTheoMaLoai(Nullable<int> maLoaiMay)
        {
            var maLoaiMayParameter = maLoaiMay.HasValue ?
                new ObjectParameter("MaLoaiMay", maLoaiMay) :
                new ObjectParameter("MaLoaiMay", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<proc_layMayTheoMaLoai_Result>("proc_layMayTheoMaLoai", maLoaiMayParameter);
        }
    
        public virtual ObjectResult<proc_LayTTNVDangNhap_Result> proc_LayTTNVDangNhap()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<proc_LayTTNVDangNhap_Result>("proc_LayTTNVDangNhap");
        }
    
        public virtual int proc_MoKhoaTaiKhoan(string tenDangNhap)
        {
            var tenDangNhapParameter = tenDangNhap != null ?
                new ObjectParameter("TenDangNhap", tenDangNhap) :
                new ObjectParameter("TenDangNhap", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("proc_MoKhoaTaiKhoan", tenDangNhapParameter);
        }
    
        public virtual int proc_SuaDVDoAn(string maDV, string tenDoAn, Nullable<int> donGia, Nullable<bool> bestSeller, string trangThai)
        {
            var maDVParameter = maDV != null ?
                new ObjectParameter("MaDV", maDV) :
                new ObjectParameter("MaDV", typeof(string));
    
            var tenDoAnParameter = tenDoAn != null ?
                new ObjectParameter("TenDoAn", tenDoAn) :
                new ObjectParameter("TenDoAn", typeof(string));
    
            var donGiaParameter = donGia.HasValue ?
                new ObjectParameter("DonGia", donGia) :
                new ObjectParameter("DonGia", typeof(int));
    
            var bestSellerParameter = bestSeller.HasValue ?
                new ObjectParameter("BestSeller", bestSeller) :
                new ObjectParameter("BestSeller", typeof(bool));
    
            var trangThaiParameter = trangThai != null ?
                new ObjectParameter("TrangThai", trangThai) :
                new ObjectParameter("TrangThai", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("proc_SuaDVDoAn", maDVParameter, tenDoAnParameter, donGiaParameter, bestSellerParameter, trangThaiParameter);
        }
    
        public virtual int proc_SuaDVDouong(string maDV, string tenDoUong, Nullable<int> donGia, Nullable<bool> bestSeller, string trangThai)
        {
            var maDVParameter = maDV != null ?
                new ObjectParameter("MaDV", maDV) :
                new ObjectParameter("MaDV", typeof(string));
    
            var tenDoUongParameter = tenDoUong != null ?
                new ObjectParameter("TenDoUong", tenDoUong) :
                new ObjectParameter("TenDoUong", typeof(string));
    
            var donGiaParameter = donGia.HasValue ?
                new ObjectParameter("DonGia", donGia) :
                new ObjectParameter("DonGia", typeof(int));
    
            var bestSellerParameter = bestSeller.HasValue ?
                new ObjectParameter("BestSeller", bestSeller) :
                new ObjectParameter("BestSeller", typeof(bool));
    
            var trangThaiParameter = trangThai != null ?
                new ObjectParameter("TrangThai", trangThai) :
                new ObjectParameter("TrangThai", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("proc_SuaDVDouong", maDVParameter, tenDoUongParameter, donGiaParameter, bestSellerParameter, trangThaiParameter);
        }
    
        public virtual int proc_SuaDVTheCao(string maDV, string loaiThe, Nullable<int> menhGia)
        {
            var maDVParameter = maDV != null ?
                new ObjectParameter("MaDV", maDV) :
                new ObjectParameter("MaDV", typeof(string));
    
            var loaiTheParameter = loaiThe != null ?
                new ObjectParameter("LoaiThe", loaiThe) :
                new ObjectParameter("LoaiThe", typeof(string));
    
            var menhGiaParameter = menhGia.HasValue ?
                new ObjectParameter("MenhGia", menhGia) :
                new ObjectParameter("MenhGia", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("proc_SuaDVTheCao", maDVParameter, loaiTheParameter, menhGiaParameter);
        }
    
        public virtual int proc_suaLinhKien(Nullable<int> maLoaiMay, string tenLinhKien, string chiTietLK, Nullable<int> soLuong)
        {
            var maLoaiMayParameter = maLoaiMay.HasValue ?
                new ObjectParameter("MaLoaiMay", maLoaiMay) :
                new ObjectParameter("MaLoaiMay", typeof(int));
    
            var tenLinhKienParameter = tenLinhKien != null ?
                new ObjectParameter("TenLinhKien", tenLinhKien) :
                new ObjectParameter("TenLinhKien", typeof(string));
    
            var chiTietLKParameter = chiTietLK != null ?
                new ObjectParameter("ChiTietLK", chiTietLK) :
                new ObjectParameter("ChiTietLK", typeof(string));
    
            var soLuongParameter = soLuong.HasValue ?
                new ObjectParameter("SoLuong", soLuong) :
                new ObjectParameter("SoLuong", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("proc_suaLinhKien", maLoaiMayParameter, tenLinhKienParameter, chiTietLKParameter, soLuongParameter);
        }
    
        public virtual int proc_suaLoaiMay(Nullable<int> maLoaiMay, string tenLoaiMay, Nullable<int> soTienMotGio)
        {
            var maLoaiMayParameter = maLoaiMay.HasValue ?
                new ObjectParameter("MaLoaiMay", maLoaiMay) :
                new ObjectParameter("MaLoaiMay", typeof(int));
    
            var tenLoaiMayParameter = tenLoaiMay != null ?
                new ObjectParameter("TenLoaiMay", tenLoaiMay) :
                new ObjectParameter("TenLoaiMay", typeof(string));
    
            var soTienMotGioParameter = soTienMotGio.HasValue ?
                new ObjectParameter("SoTienMotGio", soTienMotGio) :
                new ObjectParameter("SoTienMotGio", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("proc_suaLoaiMay", maLoaiMayParameter, tenLoaiMayParameter, soTienMotGioParameter);
        }
    
        public virtual int proc_suaMayTinh(string soMay, string trangThai, Nullable<int> maLoaiMay)
        {
            var soMayParameter = soMay != null ?
                new ObjectParameter("SoMay", soMay) :
                new ObjectParameter("SoMay", typeof(string));
    
            var trangThaiParameter = trangThai != null ?
                new ObjectParameter("TrangThai", trangThai) :
                new ObjectParameter("TrangThai", typeof(string));
    
            var maLoaiMayParameter = maLoaiMay.HasValue ?
                new ObjectParameter("MaLoaiMay", maLoaiMay) :
                new ObjectParameter("MaLoaiMay", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("proc_suaMayTinh", soMayParameter, trangThaiParameter, maLoaiMayParameter);
        }
    
        public virtual ObjectResult<string> proc_TaiKhoanSuDungMay(string maMay)
        {
            var maMayParameter = maMay != null ?
                new ObjectParameter("MaMay", maMay) :
                new ObjectParameter("MaMay", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("proc_TaiKhoanSuDungMay", maMayParameter);
        }
    
        public virtual ObjectResult<string> proc_TaoHoaDonDichVu(string phuongThucTT, Nullable<int> maNV, string maKM, Nullable<int> tongThanhToan)
        {
            var phuongThucTTParameter = phuongThucTT != null ?
                new ObjectParameter("PhuongThucTT", phuongThucTT) :
                new ObjectParameter("PhuongThucTT", typeof(string));
    
            var maNVParameter = maNV.HasValue ?
                new ObjectParameter("MaNV", maNV) :
                new ObjectParameter("MaNV", typeof(int));
    
            var maKMParameter = maKM != null ?
                new ObjectParameter("MaKM", maKM) :
                new ObjectParameter("MaKM", typeof(string));
    
            var tongThanhToanParameter = tongThanhToan.HasValue ?
                new ObjectParameter("TongThanhToan", tongThanhToan) :
                new ObjectParameter("TongThanhToan", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("proc_TaoHoaDonDichVu", phuongThucTTParameter, maNVParameter, maKMParameter, tongThanhToanParameter);
        }
    
        public virtual int proc_taoTk(string sDT, string matKhau)
        {
            var sDTParameter = sDT != null ?
                new ObjectParameter("SDT", sDT) :
                new ObjectParameter("SDT", typeof(string));
    
            var matKhauParameter = matKhau != null ?
                new ObjectParameter("MatKhau", matKhau) :
                new ObjectParameter("MatKhau", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("proc_taoTk", sDTParameter, matKhauParameter);
        }
    
        public virtual int proc_ThemDichVuVaoHoaDon(string maHD, string maDV, Nullable<int> donGia, Nullable<int> soLuong)
        {
            var maHDParameter = maHD != null ?
                new ObjectParameter("MaHD", maHD) :
                new ObjectParameter("MaHD", typeof(string));
    
            var maDVParameter = maDV != null ?
                new ObjectParameter("MaDV", maDV) :
                new ObjectParameter("MaDV", typeof(string));
    
            var donGiaParameter = donGia.HasValue ?
                new ObjectParameter("DonGia", donGia) :
                new ObjectParameter("DonGia", typeof(int));
    
            var soLuongParameter = soLuong.HasValue ?
                new ObjectParameter("SoLuong", soLuong) :
                new ObjectParameter("SoLuong", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("proc_ThemDichVuVaoHoaDon", maHDParameter, maDVParameter, donGiaParameter, soLuongParameter);
        }
    
        public virtual int proc_ThemDVDoAn(string tenDoAn, Nullable<int> donGia, Nullable<bool> bestSeller)
        {
            var tenDoAnParameter = tenDoAn != null ?
                new ObjectParameter("TenDoAn", tenDoAn) :
                new ObjectParameter("TenDoAn", typeof(string));
    
            var donGiaParameter = donGia.HasValue ?
                new ObjectParameter("DonGia", donGia) :
                new ObjectParameter("DonGia", typeof(int));
    
            var bestSellerParameter = bestSeller.HasValue ?
                new ObjectParameter("BestSeller", bestSeller) :
                new ObjectParameter("BestSeller", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("proc_ThemDVDoAn", tenDoAnParameter, donGiaParameter, bestSellerParameter);
        }
    
        public virtual int proc_ThemDVDouong(string tenDoUong, Nullable<int> donGia, Nullable<bool> bestSeller)
        {
            var tenDoUongParameter = tenDoUong != null ?
                new ObjectParameter("TenDoUong", tenDoUong) :
                new ObjectParameter("TenDoUong", typeof(string));
    
            var donGiaParameter = donGia.HasValue ?
                new ObjectParameter("DonGia", donGia) :
                new ObjectParameter("DonGia", typeof(int));
    
            var bestSellerParameter = bestSeller.HasValue ?
                new ObjectParameter("BestSeller", bestSeller) :
                new ObjectParameter("BestSeller", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("proc_ThemDVDouong", tenDoUongParameter, donGiaParameter, bestSellerParameter);
        }
    
        public virtual int proc_ThemDVTheCao(string loaiThe, Nullable<int> menhGia)
        {
            var loaiTheParameter = loaiThe != null ?
                new ObjectParameter("LoaiThe", loaiThe) :
                new ObjectParameter("LoaiThe", typeof(string));
    
            var menhGiaParameter = menhGia.HasValue ?
                new ObjectParameter("MenhGia", menhGia) :
                new ObjectParameter("MenhGia", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("proc_ThemDVTheCao", loaiTheParameter, menhGiaParameter);
        }
    
        public virtual ObjectResult<string> proc_ThemHoaDonNapTien(Nullable<int> tongThanhToan, string phuongThucTT, Nullable<int> soTienNap, string tenDangNhap, Nullable<int> maNV, string maKM)
        {
            var tongThanhToanParameter = tongThanhToan.HasValue ?
                new ObjectParameter("TongThanhToan", tongThanhToan) :
                new ObjectParameter("TongThanhToan", typeof(int));
    
            var phuongThucTTParameter = phuongThucTT != null ?
                new ObjectParameter("PhuongThucTT", phuongThucTT) :
                new ObjectParameter("PhuongThucTT", typeof(string));
    
            var soTienNapParameter = soTienNap.HasValue ?
                new ObjectParameter("SoTienNap", soTienNap) :
                new ObjectParameter("SoTienNap", typeof(int));
    
            var tenDangNhapParameter = tenDangNhap != null ?
                new ObjectParameter("TenDangNhap", tenDangNhap) :
                new ObjectParameter("TenDangNhap", typeof(string));
    
            var maNVParameter = maNV.HasValue ?
                new ObjectParameter("MaNV", maNV) :
                new ObjectParameter("MaNV", typeof(int));
    
            var maKMParameter = maKM != null ?
                new ObjectParameter("MaKM", maKM) :
                new ObjectParameter("MaKM", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("proc_ThemHoaDonNapTien", tongThanhToanParameter, phuongThucTTParameter, soTienNapParameter, tenDangNhapParameter, maNVParameter, maKMParameter);
        }
    
        public virtual int proc_themLinhKien(Nullable<int> maLoaiMay, string tenLinhKien, string chiTietLK, Nullable<int> soLuong)
        {
            var maLoaiMayParameter = maLoaiMay.HasValue ?
                new ObjectParameter("MaLoaiMay", maLoaiMay) :
                new ObjectParameter("MaLoaiMay", typeof(int));
    
            var tenLinhKienParameter = tenLinhKien != null ?
                new ObjectParameter("TenLinhKien", tenLinhKien) :
                new ObjectParameter("TenLinhKien", typeof(string));
    
            var chiTietLKParameter = chiTietLK != null ?
                new ObjectParameter("ChiTietLK", chiTietLK) :
                new ObjectParameter("ChiTietLK", typeof(string));
    
            var soLuongParameter = soLuong.HasValue ?
                new ObjectParameter("SoLuong", soLuong) :
                new ObjectParameter("SoLuong", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("proc_themLinhKien", maLoaiMayParameter, tenLinhKienParameter, chiTietLKParameter, soLuongParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> proc_themLoaiMay(string tenLoaiMay, Nullable<int> soTienMotGio)
        {
            var tenLoaiMayParameter = tenLoaiMay != null ?
                new ObjectParameter("TenLoaiMay", tenLoaiMay) :
                new ObjectParameter("TenLoaiMay", typeof(string));
    
            var soTienMotGioParameter = soTienMotGio.HasValue ?
                new ObjectParameter("SoTienMotGio", soTienMotGio) :
                new ObjectParameter("SoTienMotGio", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("proc_themLoaiMay", tenLoaiMayParameter, soTienMotGioParameter);
        }
    
        public virtual int proc_themMayTinh(Nullable<System.DateTime> ngayLapDat, Nullable<int> maLoaiMay)
        {
            var ngayLapDatParameter = ngayLapDat.HasValue ?
                new ObjectParameter("NgayLapDat", ngayLapDat) :
                new ObjectParameter("NgayLapDat", typeof(System.DateTime));
    
            var maLoaiMayParameter = maLoaiMay.HasValue ?
                new ObjectParameter("MaLoaiMay", maLoaiMay) :
                new ObjectParameter("MaLoaiMay", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("proc_themMayTinh", ngayLapDatParameter, maLoaiMayParameter);
        }
    
        public virtual ObjectResult<proc_TimKhuyenMai_Result> proc_TimKhuyenMai(Nullable<System.DateTime> startDate, Nullable<System.DateTime> endDate, string query)
        {
            var startDateParameter = startDate.HasValue ?
                new ObjectParameter("StartDate", startDate) :
                new ObjectParameter("StartDate", typeof(System.DateTime));
    
            var endDateParameter = endDate.HasValue ?
                new ObjectParameter("EndDate", endDate) :
                new ObjectParameter("EndDate", typeof(System.DateTime));
    
            var queryParameter = query != null ?
                new ObjectParameter("Query", query) :
                new ObjectParameter("Query", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<proc_TimKhuyenMai_Result>("proc_TimKhuyenMai", startDateParameter, endDateParameter, queryParameter);
        }
    
        public virtual ObjectResult<proc_TimKiemHoaDon_Result> proc_TimKiemHoaDon(Nullable<System.DateTime> ngayBatDau, Nullable<System.DateTime> ngayKetThuc, string loaiHoaDon, string maHD)
        {
            var ngayBatDauParameter = ngayBatDau.HasValue ?
                new ObjectParameter("NgayBatDau", ngayBatDau) :
                new ObjectParameter("NgayBatDau", typeof(System.DateTime));
    
            var ngayKetThucParameter = ngayKetThuc.HasValue ?
                new ObjectParameter("NgayKetThuc", ngayKetThuc) :
                new ObjectParameter("NgayKetThuc", typeof(System.DateTime));
    
            var loaiHoaDonParameter = loaiHoaDon != null ?
                new ObjectParameter("LoaiHoaDon", loaiHoaDon) :
                new ObjectParameter("LoaiHoaDon", typeof(string));
    
            var maHDParameter = maHD != null ?
                new ObjectParameter("MaHD", maHD) :
                new ObjectParameter("MaHD", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<proc_TimKiemHoaDon_Result>("proc_TimKiemHoaDon", ngayBatDauParameter, ngayKetThucParameter, loaiHoaDonParameter, maHDParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> proc_TinhDoanhThuThangNay()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("proc_TinhDoanhThuThangNay");
        }
    
        public virtual int proc_XoaDV(string maDV)
        {
            var maDVParameter = maDV != null ?
                new ObjectParameter("MaDV", maDV) :
                new ObjectParameter("MaDV", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("proc_XoaDV", maDVParameter);
        }
    
        public virtual int proc_xoaLinhKien(Nullable<int> maLoaiMay, string tenLinhKien)
        {
            var maLoaiMayParameter = maLoaiMay.HasValue ?
                new ObjectParameter("MaLoaiMay", maLoaiMay) :
                new ObjectParameter("MaLoaiMay", typeof(int));
    
            var tenLinhKienParameter = tenLinhKien != null ?
                new ObjectParameter("TenLinhKien", tenLinhKien) :
                new ObjectParameter("TenLinhKien", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("proc_xoaLinhKien", maLoaiMayParameter, tenLinhKienParameter);
        }
    
        public virtual int proc_xoaLoaiMay(Nullable<int> maLoaiMay)
        {
            var maLoaiMayParameter = maLoaiMay.HasValue ?
                new ObjectParameter("MaLoaiMay", maLoaiMay) :
                new ObjectParameter("MaLoaiMay", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("proc_xoaLoaiMay", maLoaiMayParameter);
        }
    
        public virtual int sp_BatDauSuDungMay(string tenDangNhap, string soMay)
        {
            var tenDangNhapParameter = tenDangNhap != null ?
                new ObjectParameter("TenDangNhap", tenDangNhap) :
                new ObjectParameter("TenDangNhap", typeof(string));
    
            var soMayParameter = soMay != null ?
                new ObjectParameter("SoMay", soMay) :
                new ObjectParameter("SoMay", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_BatDauSuDungMay", tenDangNhapParameter, soMayParameter);
        }
    
        public virtual int sp_DeleteKhuyenMai(string maKM)
        {
            var maKMParameter = maKM != null ?
                new ObjectParameter("MaKM", maKM) :
                new ObjectParameter("MaKM", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_DeleteKhuyenMai", maKMParameter);
        }
    
        public virtual int sp_InsertKhuyenMai(string tenChTrinh, Nullable<int> tyLeKM, Nullable<int> soTienToiThieuApDung, Nullable<int> kMToiDa, Nullable<System.DateTime> thoiGianBatDau, Nullable<System.DateTime> thoiGianKetThuc, Nullable<int> maLoaiKM)
        {
            var tenChTrinhParameter = tenChTrinh != null ?
                new ObjectParameter("TenChTrinh", tenChTrinh) :
                new ObjectParameter("TenChTrinh", typeof(string));
    
            var tyLeKMParameter = tyLeKM.HasValue ?
                new ObjectParameter("TyLeKM", tyLeKM) :
                new ObjectParameter("TyLeKM", typeof(int));
    
            var soTienToiThieuApDungParameter = soTienToiThieuApDung.HasValue ?
                new ObjectParameter("SoTienToiThieuApDung", soTienToiThieuApDung) :
                new ObjectParameter("SoTienToiThieuApDung", typeof(int));
    
            var kMToiDaParameter = kMToiDa.HasValue ?
                new ObjectParameter("KMToiDa", kMToiDa) :
                new ObjectParameter("KMToiDa", typeof(int));
    
            var thoiGianBatDauParameter = thoiGianBatDau.HasValue ?
                new ObjectParameter("ThoiGianBatDau", thoiGianBatDau) :
                new ObjectParameter("ThoiGianBatDau", typeof(System.DateTime));
    
            var thoiGianKetThucParameter = thoiGianKetThuc.HasValue ?
                new ObjectParameter("ThoiGianKetThuc", thoiGianKetThuc) :
                new ObjectParameter("ThoiGianKetThuc", typeof(System.DateTime));
    
            var maLoaiKMParameter = maLoaiKM.HasValue ?
                new ObjectParameter("MaLoaiKM", maLoaiKM) :
                new ObjectParameter("MaLoaiKM", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_InsertKhuyenMai", tenChTrinhParameter, tyLeKMParameter, soTienToiThieuApDungParameter, kMToiDaParameter, thoiGianBatDauParameter, thoiGianKetThucParameter, maLoaiKMParameter);
        }
    
        public virtual int sp_KetThucSuDungMay(string tenDangNhap, string soMay)
        {
            var tenDangNhapParameter = tenDangNhap != null ?
                new ObjectParameter("TenDangNhap", tenDangNhap) :
                new ObjectParameter("TenDangNhap", typeof(string));
    
            var soMayParameter = soMay != null ?
                new ObjectParameter("SoMay", soMay) :
                new ObjectParameter("SoMay", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_KetThucSuDungMay", tenDangNhapParameter, soMayParameter);
        }
    
        public virtual int sp_KiemTraSoDuTaiKhoan()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_KiemTraSoDuTaiKhoan");
        }
    
        public virtual int sp_SuaNhanVien(Nullable<int> maNV, string hoTen, string diaChi, string gioiTinh, Nullable<System.DateTime> ngaySinh)
        {
            var maNVParameter = maNV.HasValue ?
                new ObjectParameter("MaNV", maNV) :
                new ObjectParameter("MaNV", typeof(int));
    
            var hoTenParameter = hoTen != null ?
                new ObjectParameter("HoTen", hoTen) :
                new ObjectParameter("HoTen", typeof(string));
    
            var diaChiParameter = diaChi != null ?
                new ObjectParameter("DiaChi", diaChi) :
                new ObjectParameter("DiaChi", typeof(string));
    
            var gioiTinhParameter = gioiTinh != null ?
                new ObjectParameter("GioiTinh", gioiTinh) :
                new ObjectParameter("GioiTinh", typeof(string));
    
            var ngaySinhParameter = ngaySinh.HasValue ?
                new ObjectParameter("NgaySinh", ngaySinh) :
                new ObjectParameter("NgaySinh", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_SuaNhanVien", maNVParameter, hoTenParameter, diaChiParameter, gioiTinhParameter, ngaySinhParameter);
        }
    
        public virtual int sp_SuaTaiKhoan(string tenDangNhap, string matKhau, Nullable<long> soDu)
        {
            var tenDangNhapParameter = tenDangNhap != null ?
                new ObjectParameter("TenDangNhap", tenDangNhap) :
                new ObjectParameter("TenDangNhap", typeof(string));
    
            var matKhauParameter = matKhau != null ?
                new ObjectParameter("MatKhau", matKhau) :
                new ObjectParameter("MatKhau", typeof(string));
    
            var soDuParameter = soDu.HasValue ?
                new ObjectParameter("SoDu", soDu) :
                new ObjectParameter("SoDu", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_SuaTaiKhoan", tenDangNhapParameter, matKhauParameter, soDuParameter);
        }
    
        public virtual int sp_ThemNhanVien(string hoTen, string sDT, string diaChi, string gioiTinh, Nullable<System.DateTime> ngaySinh)
        {
            var hoTenParameter = hoTen != null ?
                new ObjectParameter("HoTen", hoTen) :
                new ObjectParameter("HoTen", typeof(string));
    
            var sDTParameter = sDT != null ?
                new ObjectParameter("SDT", sDT) :
                new ObjectParameter("SDT", typeof(string));
    
            var diaChiParameter = diaChi != null ?
                new ObjectParameter("DiaChi", diaChi) :
                new ObjectParameter("DiaChi", typeof(string));
    
            var gioiTinhParameter = gioiTinh != null ?
                new ObjectParameter("GioiTinh", gioiTinh) :
                new ObjectParameter("GioiTinh", typeof(string));
    
            var ngaySinhParameter = ngaySinh.HasValue ?
                new ObjectParameter("NgaySinh", ngaySinh) :
                new ObjectParameter("NgaySinh", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_ThemNhanVien", hoTenParameter, sDTParameter, diaChiParameter, gioiTinhParameter, ngaySinhParameter);
        }
    
        public virtual int sp_ThemTaiKhoan(string tenDangNhap, Nullable<long> soDu)
        {
            var tenDangNhapParameter = tenDangNhap != null ?
                new ObjectParameter("TenDangNhap", tenDangNhap) :
                new ObjectParameter("TenDangNhap", typeof(string));
    
            var soDuParameter = soDu.HasValue ?
                new ObjectParameter("SoDu", soDu) :
                new ObjectParameter("SoDu", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_ThemTaiKhoan", tenDangNhapParameter, soDuParameter);
        }
    
        public virtual ObjectResult<sp_TinhTongThoiGianSuDungTatCaTaiKhoan_Result> sp_TinhTongThoiGianSuDungTatCaTaiKhoan(Nullable<int> thang, Nullable<int> nam)
        {
            var thangParameter = thang.HasValue ?
                new ObjectParameter("Thang", thang) :
                new ObjectParameter("Thang", typeof(int));
    
            var namParameter = nam.HasValue ?
                new ObjectParameter("Nam", nam) :
                new ObjectParameter("Nam", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_TinhTongThoiGianSuDungTatCaTaiKhoan_Result>("sp_TinhTongThoiGianSuDungTatCaTaiKhoan", thangParameter, namParameter);
        }
    
        public virtual int sp_UpdateKhuyenMai(string maKM, string tenChTrinh, Nullable<int> tyLeKM, Nullable<int> soTienToiThieuApDung, Nullable<int> kMToiDa, Nullable<System.DateTime> thoiGianBatDau, Nullable<System.DateTime> thoiGianKetThuc, Nullable<int> maLoaiKM)
        {
            var maKMParameter = maKM != null ?
                new ObjectParameter("MaKM", maKM) :
                new ObjectParameter("MaKM", typeof(string));
    
            var tenChTrinhParameter = tenChTrinh != null ?
                new ObjectParameter("TenChTrinh", tenChTrinh) :
                new ObjectParameter("TenChTrinh", typeof(string));
    
            var tyLeKMParameter = tyLeKM.HasValue ?
                new ObjectParameter("TyLeKM", tyLeKM) :
                new ObjectParameter("TyLeKM", typeof(int));
    
            var soTienToiThieuApDungParameter = soTienToiThieuApDung.HasValue ?
                new ObjectParameter("SoTienToiThieuApDung", soTienToiThieuApDung) :
                new ObjectParameter("SoTienToiThieuApDung", typeof(int));
    
            var kMToiDaParameter = kMToiDa.HasValue ?
                new ObjectParameter("KMToiDa", kMToiDa) :
                new ObjectParameter("KMToiDa", typeof(int));
    
            var thoiGianBatDauParameter = thoiGianBatDau.HasValue ?
                new ObjectParameter("ThoiGianBatDau", thoiGianBatDau) :
                new ObjectParameter("ThoiGianBatDau", typeof(System.DateTime));
    
            var thoiGianKetThucParameter = thoiGianKetThuc.HasValue ?
                new ObjectParameter("ThoiGianKetThuc", thoiGianKetThuc) :
                new ObjectParameter("ThoiGianKetThuc", typeof(System.DateTime));
    
            var maLoaiKMParameter = maLoaiKM.HasValue ?
                new ObjectParameter("MaLoaiKM", maLoaiKM) :
                new ObjectParameter("MaLoaiKM", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_UpdateKhuyenMai", maKMParameter, tenChTrinhParameter, tyLeKMParameter, soTienToiThieuApDungParameter, kMToiDaParameter, thoiGianBatDauParameter, thoiGianKetThucParameter, maLoaiKMParameter);
        }
    
        public virtual int sp_XoaNhanVien(Nullable<int> maNV)
        {
            var maNVParameter = maNV.HasValue ?
                new ObjectParameter("MaNV", maNV) :
                new ObjectParameter("MaNV", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_XoaNhanVien", maNVParameter);
        }
    }
}
